### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by mykola-fant-ztu** [FullmetalBober/ProgressHub#2]
- this menu does not do anything 
![image](https://github.com/FullmetalBober/ProgressHub/assets/124682530/f6af87c6-2e42-4b96-a204-8734ac66ebf5)

- "My Issues" leads to 404 
![image](https://github.com/FullmetalBober/ProgressHub/assets/124682530/124e2782-b825-4e7f-b537-0a5402feb735)

- the functionality of this page is not clear for me 
![image](https://github.com/FullmetalBober/ProgressHub/assets/124682530/c85ce279-542a-4d8f-9ab0-3d1cfa2c0275)

- pretty high but requires attention 
![image](https://github.com/FullmetalBober/ProgressHub/assets/124682530/457a22e6-772e-4f86-8ef8-114de130f04f)

- Terms of Service is 404 as well
- "Sign up for free" does not work

**Comment by FullmetalBober** [comment]
Yeap, i know about this 404 pages, it will be implemented in nearest future (summer)😋
The idea behind this project, is for tracking team issues, so this editor will be used for description editing. As for low optimisation for this page, if you open two instances of this in different windows, you find out, that this editor supports live update, so i think it's impossible(or very hard) to implement better optimisation

**Comment by FullmetalBober** [comment]
Oh, thanks, I already forgot about "Sign up for free" button😅
